version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
  clickhouse01:
    image: clickhouse/clickhouse-server:22.8.12.45
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:22.8.12.45
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse-init:
    image: clickhouse/clickhouse-server:22.8.12.45
    container_name: clickhouse-init
    hostname: clickhouse-init
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.15
    volumes:
      - ${PWD}/clickhouse-init:/var/clickhouse
    depends_on:
      - clickhouse01
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      while ! clickhouse-client --host clickhouse01 -q 'SHOW databases;'; do
          echo waiting for clickhouse up
          sleep 1
      done

      clickhouse-client --host clickhouse01 --queries-file /var/clickhouse/init_database.sql
      "

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
